### ISSUE TITLE
Nat32 seems to box using the wrong threshold

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#2774] opened 2021-09-09 16:22 UTC
``` ocaml
  let box env = Func.share_code1 env "box_i32" ("n", I32Type) [I32Type] (fun env get_n ->
      get_n ^^ compile_unboxed_const (Int32.of_int (1 lsl 30)) ^^
```
It seems to me that the threshold should now be `1 lsl 31`, as the pointer key bit is the least significant one (as opposed to formerly being the second LSBit).

Needs to be cross-checked with `Nat/Int64` and `Int32` too.

**Comment by nomeata** [comment] 2021-09-09 20:50
Maybe due to this comment, in compile.ml

> This means we can store a small unboxed scalar x as (x `lsl` 1), and still
>      tell it apart from a pointer by looking at the last bits: if set, it is a
>      pointer.
>      Small here means -2^30 ≤ x < 2^30, and untagging needs to happen with an
>      _arithmetic_ right shift. This is the right thing to do for signed
>      numbers, and because we want to apply a consistent logic for all types,
>      especially as there is only one wasm type, we use the same range for
>      signed numbers as well.

**Comment by nomeata** [comment] 2021-09-09 21:05
In other words, so far we do unboxing based on the semantic value, not the bit value, and the same range for all types. This way, for example, converting between types can leave unboxed values as they are. (But the real reason is that I was too worried about getting the cornercases wrong, so I stayed conservative). So maybe the alternative is sound and doable.

**Comment by nomeata** [comment] 2022-01-10 17:08
I think we can close this; works as intended.

**Closed by nomeata** 2022-01-10 17:08 UTC
