### ISSUE TITLE
Compiler bug

### ISSUE THREAD

**Issue by credfeto** [dfinity/motoko#2599] opened 2021-06-16 09:19 UTC
Just encountered this error:

```
The build step failed for canister 'renrk-eyaaa-aaaaa-aaada-cai' with an embedded error: The command '"/home/markr/.cache/dfinity/versions/0.7.1/moc" "/home/markr/work/dfinity/main.mo" "-o" "/home/markr/work/dfinity/.dfx/local/canisters/exchange/exchange.did" "--idl" "--actor-idl" "/home/markr/work/dfinity/.dfx/local/canisters/idl/" "--actor-alias" "exchange" "renrk-eyaaa-aaaaa-aaada-cai" "--actor-alias" "token" "rkp4c-7iaaa-aaaaa-aaaca-cai" "--actor-alias" "token_assets" "rno2w-sqaaa-aaaaa-aaacq-cai" "--package" "base" "/home/markr/.cache/dfinity/versions/0.7.1/base"' failed with exit status 'exit code: 2'.
Stdout:

Stderr:
OOPS! You've triggered a compiler bug.
Please report this Motoko issue at forum.dfinity.org with the following details:

Motoko (revision 742az5xm-apvj2nq2-i96m0rlr-n1npyb43)

Fatal error: exception "Assert_failure mo_idl/idl_to_mo.ml:106:9"
Raised at file "mo_idl/idl_to_mo.ml", line 106, characters 9-21
Called from file "pipeline/pipeline.ml", line 345, characters 14-61
Called from file "lang_utils/diag.ml", line 32, characters 27-30
Called from file "lang_utils/diag.ml", line 48, characters 20-25
Called from file "lang_utils/diag.ml", line 32, characters 27-30
Called from file "pipeline/pipeline.ml" (inlined), line 356, characters 20-42
Called from file "pipeline/pipeline.ml", line 358, characters 47-63
Called from file "pipeline/pipeline.ml", line 366, characters 21-52
Called from file "lang_utils/diag.ml", line 32, characters 27-30
Called from file "lang_utils/diag.ml", line 32, characters 27-30
Called from file "pipeline/pipeline.ml", line 446, characters 27-71
Called from file "exes/moc.ml", line 136, characters 24-53
Called from file "exes/moc.ml", line 205, characters 4-23
```

This is with dfx 0.7.1

**Comment by nomeata** [comment] 2021-06-16 09:24
Thanks for the report! It is actually a duplicate of https://github.com/dfinity/motoko/issues/2319, but your contribution is appreciated. I hope can push a fix soon.

**Comment by nomeata** [comment] 2021-06-16 09:24
duplicate of #2319

**Closed by nomeata** 2021-06-16 09:24 UTC
