### ISSUE TITLE
FR: Blob.compare is inefficient

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3725] opened 2023-01-25 12:05 UTC
Blob.mo:
```
 public func compare(blob1 : Blob, blob2 : Blob) : { #less; #equal; #greater } {
    if (blob1 < blob2) {
      #less
    } else if (blob1 == blob2) {
      #equal
    } else {
      #greater
    }
 }
```
We could use a primitive implementation to avoid doing 2 traversals.

Same applies to `Principal.compare`.

**Comment by luc-blaeser** [comment] 2023-03-31 14:36
Seems related, probably duplicate of https://github.com/dfinity/motoko/issues/3826

**Comment by nomeata** [comment] 2023-05-31 07:38
Dupe of #3826.

**Closed by nomeata** 2023-05-31 07:38 UTC
